### ISSUE TITLE
Unable to update to 0.6.3

### ISSUE THREAD

**Issue by Thrasher2020** [FunkeyFlo/ps5-mqtt#15] opened 2022-07-28 10:36 UTC
### Description of the issue

0.6.3 won't install

`22-07-28 10:15:06 INFO (SyncWorker_3) [supervisor.docker.interface] Updating image df2164f9/aarch64-addon-ps5_mqtt:0.6.2 to ghcr.io/funkeyflo/ps5-mqtt/aarch64:0.6.3
22-07-28 10:15:06 ERROR (SyncWorker_3) [supervisor.docker.addon] Invalid build environment, can't build this add-on!`

### Addon version

0.6.3

### Platform

Core 2022.07.b0

### Logs of the issue (if applicable)

22-07-28 10:15:06 INFO (SyncWorker_3) [supervisor.docker.interface] Updating image df2164f9/aarch64-addon-ps5_mqtt:0.6.2 to ghcr.io/funkeyflo/ps5-mqtt/aarch64:0.6.3
22-07-28 10:15:06 ERROR (SyncWorker_3) [supervisor.docker.addon] Invalid build environment, can't build this add-on!

**Comment by FunkeyFlo** [comment] 2022-07-28 11:25
For next time, please check whether this issue already exists. This is a duplicate of issue [#13](https://github.com/FunkeyFlo/ps5-mqtt/issues/13#issuecomment-1197693572), you can read how to resolve this there.

**Closed by FunkeyFlo** 2022-07-28 11:25 UTC
Labels: duplicate
