### ISSUE TITLE
MQTT Breaking Change Coming in 2024 

### ISSUE THREAD

**Issue by jianyu-li** [FunkeyFlo/ps5-mqtt#285] opened 2023-08-02 21:02 UTC
### Description of the issue

Receiving the following notification that says this integration will break next year. 

![image](https://github.com/FunkeyFlo/ps5-mqtt/assets/52750081/3b37af04-fa95-43e1-a1ed-01e22bbe9176)

Links to this https://developers.home-assistant.io/blog/2023-057-21-change-naming-mqtt-entities/

### Addon version

1.3.1

### Platform

Home Assistant 2023.8.0
Supervisor 2023.07.1
Operating System 10.3
Frontend 20230802.0 - latest

### Logs of the issue (if applicable)

023-08-02 12:53:43.204 WARNING (MainThread) [homeassistant.components.mqtt.mixins] MQTT entity name starts with the device name in your config {'availability': [{'topic': 'ps5-mqtt/78C881AC5F66', 'value_template': Template<template=({{ value_json.device_status }}) renders=0>, 'payload_available': 'online', 'payload_not_available': 'offline'}], 'name': 'PS5-190 power', 'command_topic': 'ps5-mqtt/78C881AC5F66/set/power', 'state_topic': 'ps5-mqtt/78C881AC5F66', 'unique_id': '78C881AC5F66_power_ps5mqtt', 'state_on': 'AWAKE', 'state_off': 'STANDBY', 'payload_on': 'AWAKE', 'payload_off': 'STANDBY', 'optimistic': False, 'value_template': Template<template=({{ value_json.power }}) renders=0>, 'icon': 'mdi:sony-playstation', 'device': {'manufacturer': 'Sony', 'model': 'Playstation 5', 'name': 'PS5-190', 'identifiers': ['78C881AC5F66'], 'connections': [['ip', '192.168.5.43']], 'sw_version': '07600007'}, 'retain': False, 'qos': 0, 'payload_available': 'online', 'availability_mode': 'latest', 'encoding': 'utf-8', 'payload_not_available': 'offline', 'enabled_by_default': True}, this is not expected. Please correct your configuration. The device name prefix will be stripped off the entity name and becomes 'Power'
2023-08-02 12:53:43.216 WARNING (MainThread) [homeassistant.components.mqtt.mixins] MQTT entity name starts with the device name in your config {'availability': [{'topic': 'ps5-mqtt/78C881AC5F66', 'value_template': Template<template=({{ value_json.device_status }}) renders=0>, 'payload_available': 'online', 'payload_not_available': 'offline'}], 'unique_id': '78C881AC5F66_activity_ps5mqtt', 'state_topic': 'ps5-mqtt/78C881AC5F66', 'name': 'PS5-190 activity', 'device': {'manufacturer': 'Sony', 'model': 'Playstation 5', 'name': 'PS5-190', 'identifiers': ['78C881AC5F66'], 'connections': [['ip', '192.168.5.43']], 'sw_version': '07600007'}, 'enabled_by_default': True, 'json_attributes_topic': 'ps5-mqtt/78C881AC5F66', 'value_template': Template<template=({{ value_json.activity }}) renders=0>, 'qos': 0, 'payload_available': 'online', 'availability_mode': 'latest', 'encoding': 'utf-8', 'payload_not_available': 'offline', 'force_update': False}, this is not expected. Please correct your configuration. The device name prefix will be stripped off the entity name and becomes 'Activity'

**Comment by FunkeyFlo** [comment] 2023-08-02 21:22
Duplicate of #282

**Closed** 2023-08-02 21:22 UTC
