### ISSUE TITLE
Discovered entities with a name that starts with the device name is no longer allowed on HA

### ISSUE THREAD

**Issue by dror1544** [FunkeyFlo/ps5-mqtt#294] opened 2023-08-19 09:25 UTC
### Description of the issue

The naming convention of HA has changed and the name of the device is no longer allowed on the entity name

refer to (https://developers.home-assistant.io/blog/2023-057-21-change-naming-mqtt-entities/) on the issue.

To my underrating, in the code of register_device.ts the device.name should be removed from the name field on both switch and sensor entities so the name should be:
name: "power" and name:  "activity" respectively
in addition, on the base entity on ha_mqtt.ts an 'has_entity_name' as mandatory attribute and it should be set to 'true' when publishing it.

### Addon version

1.3.1

### Platform

Home Assistant 2023.8.2
Supervisor 2023.08.1
Frontend 20230802.0 - latest

### Logs of the issue (if applicable)

This is a the warning I am getting from HA

Some MQTT entities have an entity name that starts with the device name. This is not expected. To avoid a duplicate name the device name prefix is stripped off the entity name as a work-a-round. Please inform the maintainer of the software application that supplies the affected entities to fix this issue.

List of affected entities:

switch.ps5_807_power
sensor.ps5_807_activity

**Comment by FunkeyFlo** [comment] 2023-08-19 10:27
I would like to kindly but firmly ask you to check whether this issue has already been created.

Duplicate of #282.

**Closed by FunkeyFlo** 2023-08-19 10:27 UTC
