### ISSUE TITLE
No devices being discovered

### ISSUE THREAD

**Issue by klatka** [FunkeyFlo/ps5-mqtt#164] opened 2022-12-20 23:09 UTC
### Description of the issue

I installed the addon and started it but this addon creates no devices:
```
Starting PS5-MQTT...
2022-12-20T22:56:15.522Z @ha:ps5:webserver Server listening on PORT: 62612
```

2nd try was to create a user in mosquitto-broker addon, set it in configuration, and set psn account. But still same log and no devices:
```
host: core-mosquitto
port: "1883"
user: <user>
pass: <pass>
```

3rd try was to add broadcast IP address. No success at all.

Do I miss something?

### Addon version

1.3.1

### Platform

Home Assistant 2022.12.7
Supervisor 2022.11.2
Operating System 9.3
Frontend 20221213.1 - latest

**Comment by FunkeyFlo** [comment] 2022-12-21 10:36
1. Are the devices _on_?
2. Do you see the devices in the `web-ui`?
3. Is MQTT discovery enabled?

**Comment by klatka** [comment] 2022-12-21 11:07
> 1. Are the devices _on_?

Yes
> 2. Do you see the devices in the `web-ui`?

No
> 3. Is MQTT discovery enabled?

Yes but MQTT Explorer shows nothing to discover. WallPanels being discovered correctly.

**Comment by FunkeyFlo** [comment] 2022-12-21 11:12
> Do you see the devices in the web-ui?
No

This means the devices cannot be located by the addon at all. So MQTT (configuration) is not the issue.

Are you using VLANs? If so, which value did you use for the broadcast IP?

**Comment by klatka** [comment] 2022-12-21 11:26
I do not use VLANs. My network is 192.168.0.0/23 and I use the regular address 192.168.1.255 for broadcasting.

**Comment by FunkeyFlo** [comment] 2022-12-22 06:48
Are you able to discover devices using the [playactor](https://github.com/dhleong/playactor) cli? (`playactor browse`)

**Comment by FunkeyFlo** [comment] 2022-12-22 12:53
> `playactor browse` returns nothing.

Than it seems the issue is with your network/router/setup, etc. Since it isn't an issue with the software I'll be closing this issue.

> Can I add my PS5 by passing the IP?

This is currently not supported. If you would like such a feature to be added, please open a [Feature Request](https://github.com/FunkeyFlo/ps5-mqtt/issues/new/choose) for it. 😊

**Closed by FunkeyFlo** 2022-12-22 12:53 UTC
Labels: question
